name: Generate Snake

on:
  schedule: # Ejecutar cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecutarlo manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: luiguie3333
          outputs: dist/snake.svg

      - name: Push generated snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
